# Generated by Django 6.0.4 on 2026-05-03 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('discord_username', models.CharField(blank=True, max_length=100)),
                ('discord_avatar', models.CharField(blank=True, max_length=200)),
                ('riot_puuid', models.CharField(blank=True, db_index=True, max_length=100)),
                ('riot_game_name', models.CharField(blank=True, max_length=64)),
                ('riot_tag_line', models.CharField(blank=True, max_length=16)),
                ('riot_summoner_id', models.CharField(blank=True, max_length=100)),
                ('riot_rank', models.CharField(blank=True, max_length=32)),
                ('role_mmr', models.JSONField(default=dict)),
                ('lp_tokens', models.IntegerField(default=0)),
                ('preferred_role', models.CharField(blank=True, choices=[('top', 'Top'), ('jgl', 'Jungle'), ('mid', 'Mid'), ('adc', 'ADC'), ('sup', 'Support')], max_length=8)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('split_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=16)),
                ('total_rounds', models.PositiveIntegerField(default=4)),
                ('current_round', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons_created', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('pending_report', 'Pending Report'), ('processing', 'Processing'), ('completed', 'Completed'), ('disputed', 'Disputed')], default='scheduled', max_length=20)),
                ('riot_match_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('discord_thread_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_matches', to='api.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.season')),
            ],
        ),
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bounty_type', models.CharField(choices=[('pentakill', 'Get a Pentakill'), ('ace', 'Ace the enemy team'), ('baron_steal', 'Steal Baron'), ('first_blood', 'Get First Blood'), ('perfect_game', 'Win with 0 deaths'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('description', models.TextField()),
                ('lp_reward', models.PositiveIntegerField(default=50)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to='api.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to='api.player')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to='api.season')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=8)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('buchholz', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to='api.player')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.season')),
            ],
            options={
                'unique_together': {('name', 'season')},
            },
        ),
        migrations.AddField(
            model_name='match',
            name='team_blue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_matches', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_matches', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='api.team'),
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('top', 'Top'), ('jgl', 'Jungle'), ('mid', 'Mid'), ('adc', 'ADC'), ('sup', 'Support')], max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to='api.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp_wagered', models.PositiveIntegerField(default=0)),
                ('payout', models.IntegerField(default=0)),
                ('settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.player')),
                ('predicted_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_wins', to='api.team')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('top', 'Top'), ('jgl', 'Jungle'), ('mid', 'Mid'), ('adc', 'ADC'), ('sup', 'Support')], max_length=8)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.team')),
            ],
            options={
                'unique_together': {('team', 'role')},
            },
        ),
    ]
