# Generated by Django 6.0.4 on 2026-05-06 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='season',
            name='match_day',
            field=models.CharField(blank=True, default='Sunday', max_length=20),
        ),
        migrations.AddField(
            model_name='season',
            name='match_time',
            field=models.CharField(blank=True, default='16:00', max_length=10),
        ),
        migrations.AddField(
            model_name='season',
            name='min_teams',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('registration', 'Registration Open'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=16),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='api.season'),
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('top', 'Top'), ('jgl', 'Jungle'), ('mid', 'Mid'), ('adc', 'ADC'), ('sup', 'Support')], max_length=8)),
                ('is_sub', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='api.team')),
            ],
            options={
                'unique_together': {('team', 'player')},
            },
        ),
    ]
